# Generated by Django 4.2.13 on 2024-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('collagename', models.CharField(max_length=100)),
                ('course_year', models.CharField(max_length=100)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
