# Generated by Django 4.2.13 on 2024-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
    ]
